### ISSUE TITLE
Where do I find a "Hello, World" example of using floatThead?

### ISSUE THREAD

**Issue by BreckCarter** [mkoryak/floatThead#408] opened 2018-03-13 13:21 UTC
All the existing examples seem to contain masses of code that demonstrates optional extras... for a newbie like me this extra code gets in the way of understanding the basics.

What I am asking for is a single complete &lt;HTML> page that demonstrates the absolute minimum requirements for adding floatThead overflow scrolling functionality to an existing &lt;TABLE>.

**Comment by mkoryak** [comment] 2018-03-13 14:21
how about this?

https://jsfiddle.net/joc8hvx0/8/

The html would look like this (create new file, paste this in there, serve with a server ideally):

```html
<html>
<head>
<!-- jquery  goes first-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<!-- floatThead goes after jquery -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/floatthead/2.1.1/jquery.floatThead.min.js"></script>

<style>
/* this style is not strictly needed, its here so you can better see the table */
table, td, th {
  border: 1px solid red;
}
table {
  border-collapse: collapse;
}
thead th {
  background-color: blue;
  color: white;
}
</style>
</head>
<body>
<table id="scroll-in-window">
  <thead>
    <tr>
      <th>Header content 1</th>
      <th>Header content 2</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Body content 1</td>
      <td>Body content 2</td>
    </tr>
     <tr>
      <td>Body content 1</td>
      <td>Body content 2</td>
    </tr>
     <tr>
      <td>Body content 1</td>
      <td>Body content 2</td>
    </tr>
     <tr>
      <td>Body content 1</td>
      <td>Body content 2</td>
    </tr>
     <tr>
      <td>Body content 1</td>
      <td>Body content 2</td>
    </tr>
     <tr>
      <td>Body content 1</td>
      <td>Body content 2</td>
    </tr>
  </tbody>
</table>



<!-- script to init floatThead on the table -->
<script>
$(function(){ //shorthand for making this function run at doc ready
// select the table, init floatThead on it
	$('#scroll-in-window').floatThead();
});
</script>

<div style="height:5000px">
<!-- 
this div is not needed, its here to make the page have a scroll bar. Without it, you wouldnt be able to scroll down and see the headers float.
-->
</div>
</body>
</html>
```

in the fiddle I dispense with the `<html>` and `<head>` elements. They are nice but not needed.

**Comment by mkoryak** [comment] 2018-03-13 14:37
Here is the same code modified for overflow scrolling:

https://jsfiddle.net/joc8hvx0/23/

**Comment by mkoryak** [comment] 2018-03-13 14:39
here is a shorter version of overflow scrolling init (the braindead edition):

https://jsfiddle.net/joc8hvx0/26/

**Comment by BreckCarter** [comment] 2018-03-13 18:07
Thank you very much, that's exactly what I was looking for.

And now this question: Is it expected behavior for *the rightmost visible
TH to be truncated*, with the underlying TD data to be visible?



​

**Comment by mkoryak** [comment] 2018-03-14 03:53
Sorry, I do not understand that question. What do you mean by truncated? Which jsfiddle example are you referring to?

**Comment by BreckCarter** [comment] 2018-03-14 13:23
Scroll down in this jsfiddle example:  https://jsfiddle.net/joc8hvx0/26/

The "Header Content 2" header gets chopped off on the right side, and you
can see the underlying "Body Content 2" text slide upwards through the
space that should be occupied by the header.

I pasted two images via gmail, maybe they didn't cross over to github.

I am attaching them, and also ccing your gmail address.

Thanks!

Breck

**Comment by mkoryak** [comment] 2018-03-14 13:56
I see, you are probably running into this open issue:
https://github.com/mkoryak/floatThead/issues/363

I never see that on a mac so I keep forgetting to fix it.

**Comment by mkoryak** [comment] 2018-03-14 16:16
does this have the same problem:

https://jsfiddle.net/joc8hvx0/36/

**Comment by BreckCarter** [comment] 2018-03-14 18:03
No, this  https://jsfiddle.net/joc8hvx0/36/ does *not* exhibit the bad
behavior on Windows 10 using Chrome, Brave, Firefox, IE and Edge.

( does that mean I'm a hipster now, "who likes running code with unreleased
features and bugs?" :)

Breck

**Comment by BreckCarter** [comment] 2018-03-14 18:10
It also looks OK in Vivaldi on Windows 10: https://jsfiddle.net/joc8hvx0/36/

**Comment by mkoryak** [comment] 2018-03-14 19:36
You may have been a hipster, but also it made me take another look at it. I pushed a fix to this here: https://github.com/mkoryak/floatThead/commit/17d734acd523fde048e640cf308e22cc0c3271dd

it is not released yet, and probably will not be for a bit (i like to release when there is more than one thing changed since last time). Feel free to continue using that workaround in the meantime.

Just keep in mind that the bug was caused by jquery 3.2.0, so if you use anything above that, you should be safe with the workaround in place.

**Closed** 2018-03-15 20:16 UTC
