### ISSUE TITLE
IE10 scroll bar issue

### ISSUE THREAD

**Issue by scriby** [mkoryak/floatThead#150] opened 2015-01-05 16:27 UTC
http://screencast.com/t/2oWXJZlfh

When the table initially loads in IE10, the vertical scrollbar is placed under the floating headers, which also causes the rows of the table to get hidden under the headers.

If I resize the window a little, it seems to correct the problem.

Have you seen anything like this before? Have any ideas what the root cause might be?

**Comment by mkoryak** [comment] 2015-01-05 16:57
I have seen this before, but not on IE10 - if you throw this on jsfiddle I can take a look in a VM

**Comment by mkoryak** [comment] 2015-01-05 18:59
check if your issue exists on the latest release

**Comment by scriby** [comment] 2015-01-05 19:26
I upgraded to 2.1.10, but the scroll bar problem still persist. I'll see if I can replicate in a fiddle.

**Comment by mkoryak** [comment] 2015-01-06 16:11
I found the reason for your row disappearing..
You are using jquery 1.7 on that fiddle, and that version does not have the `outerHeight` function. 

http://jsfiddle.net/zgft9n8s/5/
You can either switch to 1.8 or add your own outerHeight shim:

http://stackoverflow.com/questions/14635425/jquery-outerheight-bug-doesnt-work-properly-below-ver-1-8-3

**Comment by scriby** [comment] 2015-01-06 16:49
Ah, sorry about the bad fiddle. I didn't intend to pick an old version of jQuery!

**Comment by mkoryak** [comment] 2015-01-07 16:10
Ok, if you can produce a fiddle that reproduces this issue I will try to solve it

**Comment by mkoryak** [comment] 2015-01-15 14:11
you should this and see if it presents a workaround:

http://mkoryak.github.io/floatThead/examples/perfect-scrollbar/

**Comment by mkoryak** [comment] 2015-01-21 01:31
closing, reopen if you can make a fiddle.

**Closed by mkoryak** 2015-01-21 01:31 UTC
