### ISSUE TITLE
Excel export without thead

### ISSUE THREAD

**Issue by sentbyravens** [mkoryak/floatThead#187] opened 2015-04-11 12:36 UTC
I found a new bug of your script: Excel export don't work properly with it. In exported table.xls I can see only tbody content without thead. There is a part of export script (creates template for Excel):
```javascript
template = '<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40"><head><meta http-equiv="content-type" content="application/vnd.ms-excel; charset=UTF-8"><!--[if gte mso 9]><xml><x:ExcelWorkbook><x:ExcelWorksheets><x:ExcelWorksheet><x:Name>{worksheet}</x:Name><x:WorksheetOptions><x:DisplayGridlines/></x:WorksheetOptions></x:ExcelWorksheet></x:ExcelWorksheets></x:ExcelWorkbook></xml><![endif]--></head><body><table>{table}</table></body></html>'
```
If you need, I can show all script for you.
This is result:
![screenshot_23](https://cloud.githubusercontent.com/assets/11899659/7101338/845cbd56-e05d-11e4-8095-28561398c113.jpg)
Sorry for my English, hope you will understand me

**Comment by mkoryak** [comment] 2015-04-11 19:36
yes, excel export will not work because the table you are exporting from will not have a thead. you need to destroy the plugin before exporting and re-init again after the export runs. 

another alternative would be to try something like this:

```js
var $table = ...
$table.floatThead();
...

var export = function(){
   var $temp = $("<table></table>");
   $temp.append($table.floatThead("getRowGroups"));
   yourExportFunction($temp); 
}

`$table.floatThead("getRowGroups")` is explained on this page: 
http://mkoryak.github.io/floatThead/examples/hidden-columns/

**Comment by sentbyravens** [comment] 2015-04-11 19:42
I'm think 95% of web developers continue to use that script:
```Javascript
var tableToExcel = (function () {
        var uri = 'data:application/vnd.ms-excel;base64,'
        , template = '<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40"><head><meta http-equiv="content-type" content="application/vnd.ms-excel; charset=UTF-8"><!--[if gte mso 9]><xml><x:ExcelWorkbook><x:ExcelWorksheets><x:ExcelWorksheet><x:Name>{worksheet}</x:Name><x:WorksheetOptions><x:DisplayGridlines/></x:WorksheetOptions></x:ExcelWorksheet></x:ExcelWorksheets></x:ExcelWorkbook></xml><![endif]--></head><body><table>{table}</table></body></html>'
        , base64 = function (s) { return window.btoa(unescape(encodeURIComponent(s))) }
        , format = function (s, c) { return s.replace(/{(\w+)}/g, function (m, p) { return c[p]; }) }
        return function (table, name, filename) {
            if (!table.nodeType) table = document.getElementById(table)
            var ctx = { worksheet: name || 'Worksheet', table: table.innerHTML }
 
            document.getElementById("parusexcel").href = uri + base64(format(template, ctx));
            document.getElementById("parusexcel").download = filename;
            document.getElementById("parusexcel").click();
 
        }
    })()
```
Can you update your floatThead for that code?

**Comment by sentbyravens** [comment] 2015-04-11 20:05
I am tried to destroy your new table on export, but my real thead now has only your values, so it is still empty.
Export plugin name is excellentexport-1.4
Same code.

**Comment by mkoryak** [comment] 2015-04-11 20:10
No, I can not update my plugin to work with this code. My plugin works by moving the thead into a different table that is floated above the original table. It has nothing to do with exporting to excel. 

Try this:
```js
var tableToExcel = (function () {
        var uri = 'data:application/vnd.ms-excel;base64,'
        , template = '<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40"><head><meta http-equiv="content-type" content="application/vnd.ms-excel; charset=UTF-8"><!--[if gte mso 9]><xml><x:ExcelWorkbook><x:ExcelWorksheets><x:ExcelWorksheet><x:Name>{worksheet}</x:Name><x:WorksheetOptions><x:DisplayGridlines/></x:WorksheetOptions></x:ExcelWorksheet></x:ExcelWorksheets></x:ExcelWorkbook></xml><![endif]--></head><body><table>{table}</table></body></html>'
        , base64 = function (s) { return window.btoa(unescape(encodeURIComponent(s))) }
        , format = function (s, c) { return s.replace(/{(\w+)}/g, function (m, p) { return c[p]; }) }
        return function (table, name, filename) {
            if (!table.nodeType) table = document.getElementById(table)
            var $temp = $("<table></table>");
            $temp.append($table.floatThead("getRowGroups"));
            var ctx = { worksheet: name || 'Worksheet', table: $temp.html() }

            document.getElementById("parusexcel").href = uri + base64(format(template, ctx));
            document.getElementById("parusexcel").download = filename;
            document.getElementById("parusexcel").click();

        }
    })()
```

**Comment by sentbyravens** [comment] 2015-04-11 20:16
Your code won't work :(

**Comment by mkoryak** [comment] 2015-04-11 20:19
console.log `ctx` and see if `ctx.table` contains valid inner html for your table. Does this export thing work if you dont run my plugin in the first place?

I will need to see  your code on jsfiddle to help you further.

**Comment by sentbyravens** [comment] 2015-04-11 20:21
And why your replased table got width:1598px when my original have 1600px?
I can see 2 px of my original table :)
![image](https://cloud.githubusercontent.com/assets/11899659/7103132/80bc14dc-e0a1-11e4-8696-72e6529866a7.png)

**Comment by sentbyravens** [comment] 2015-04-11 20:23
Yes, code works good without plugin. OK, I will create jsfiddle

**Comment by mkoryak** [comment] 2015-04-11 20:23
I cant help you by looking at pictures. if you can reproduce this on jsfiddle I can help you further. You can type in russian if you want, I will still respond in english, i dont have a russian keyboard

**Comment by sentbyravens** [comment] 2015-04-11 21:23
https://jsfiddle.net/s0jp0ybu/

**Comment by mkoryak** [comment] 2015-04-11 22:15
the column alignment can be fixed by removing your css, which means that it can be fixed  by changing some of the css. I will look into this later.

I dont have excel on my mac, so the export looks like shit with or without my plugin. I updated the code so that it might work better for you.

I noticed that you are styling the table by id in your css. you should not do this, always style by class. see the faq for more information about this. 

https://jsfiddle.net/s0jp0ybu/4/

**Comment by sentbyravens** [comment] 2015-04-12 17:44
Thanks a lot! :)
Where I can find donation page?

**Comment by mkoryak** [comment] 2015-04-13 00:11
you can paypal me something to koryak.other@gmail.com - I got rid of the donation page because paypal takes a % of donations, but not for transfers. Thanks

**Closed by mkoryak** 2015-04-13 00:11 UTC
