### ISSUE TITLE
Feature request: an alternative mode to workaround jumpy header during scroll

### ISSUE THREAD

**Issue by motin** [mkoryak/floatThead#333] opened 2016-10-18 12:33 UTC
We have some rather large tables (based on [Handsontable](https://handsontable.com/)) and the window scroll event does not trigger fast enough compared to the framerate (or something), leading to a jumpy header during scroll. 

It takes lots of effort to make these tables lighter, and we want to use floatThead even without making them leaner. 

This is the proposed behavior in this alternative mode:
1. Upon scrolling start, the floating thead is hidden. 
2. Upon scrolling end, the floating thead is repositioned and shown.

**Comment by mkoryak** [comment] 2016-10-18 15:16
Ok,

I don't have time right now to work on this, but you can test out how it looks locally by making changes here:

https://github.com/mkoryak/floatThead/blob/master/jquery.floatThead.js#L730

change that conditional to statement to:

```js

            if(eventType == 'windowScrollDone'){
              $floatContainer.css('visibility', 'hidden');
            } else {
              $floatContainer.css('visibility', 'visible');
            }
```

that should probably accomplish what you proposed.

**Comment by timbowhite** [comment] 2016-10-24 15:37
Hi, I tried the code suggestions but didn't have much luck.

For me, the issue is most visible on firefox mobile: the thead jumps around when you quickly scroll up/down, but only prior to the thead being affixed to the top of the viewport.  Once you scroll down far enough, and the thead reaches the top of the viewport and becomes affixed, then there's no more jankiness, works great.

gif screen captures:
from http://mkoryak.github.io/floatThead/examples/window-scrolling/
![](http://i.imgur.com/Obx3rFt.gif)

from my site https://tld-list.com using floatThead v1.4.4:
![](http://i.imgur.com/PY7eDhK.gif)

This issue is probably due to using "scroll-linked effects" (ie. binding to scroll events on browsers that use async scrolling).  Firefox gives a console warning when using scroll-linked effects and points to this:
https://developer.mozilla.org/en-US/docs/Mozilla/Performance/Scroll-linked_effects

I made rudimentary attempts at using both of their suggested implementations( ```position: 'sticky'``` , "scroll snapping") but neither seemed to work.

BTW thanks for the plugin, definitely the best "sticky table header" plugin out there.

**Comment by mkoryak** [comment] 2016-10-25 02:18
I looked at that async scrolling article on mdn. Its pretty useless. If `position:sticky` was the real solution, then this plugin would not be needed. They also give some other suggestion which relies on non-standard or non-implemented techniques. 

You should try playing with the value of the `position` option this plugin takes. Changing it might yield better scrolling performance (or might not)

Good luck.

Ill look into implementing this suggestion when I have time for enhancements again.

**Comment by mkoryak** [comment] 2016-10-26 16:57
this page has 4 of 6 different scrolling/positioning modes on a single page:

http://mkoryak.github.io/floatThead/examples/caption-tag/

see what one looks least horrible to you. (it missing the responsive container modes, but those dont apply to you anyway)

**Comment by timbowhite** [comment] 2016-10-27 12:59
Thanks. Tested using firefox mobile 49 on a Moto G4.  Overall, fixed vs. absolute positioning was about the same.

fixed:
![](http://i.imgur.com/4Zmm9xO.gif)

absolute:
![](http://i.imgur.com/ynEe4wY.gif)

With fixed, the thead jumps around only before being affixed.  Once affixed, then its display is solid.
With absolute, the thead jumps a bit after being affixed.

When I get some more time I'll take a closer look and see if I can whip up a PR.

**Comment by mkoryak** [comment] 2016-11-02 18:00
also tell me if adding this helps:

`$window.on(eventName('wheel'), windowScrollEvent);`

right under the line that does this:

`$window.on(eventName('scroll'), windowScrollEvent);`

**Comment by timbowhite** [comment] 2016-11-03 11:40
Tried it, didnt seem to have any effect:
```
      } else { //window scrolling
        $responsiveContainer.on(eventName('scroll'), containerScrollEvent);
        $window.on(eventName('scroll'), windowScrollEvent);
        $window.on(eventName('wheel'), windowScrollEvent);
      }
```

**Comment by mkoryak** [comment] 2017-01-25 03:46
any updates here? I am going to close this for now

**Closed by mkoryak** 2017-01-25 03:46 UTC
Labels: enhancement

**Comment by timbowhite** [comment] 2017-02-25 20:15
Finally got around to looking at this. Seems the issue is that shitty browsers and cheap phones don't like having the thead's position set on scroll events.

So I changed the code a bit to only float and position the thead when necessary: when the top of the viewport is within the vertical bounds of the table.  If the viewport hasn't reached the top of the table yet, or has passed the bottom of the table, it unfloats the thead.

It's not perfect, but i think it's an improvement, screen cap: https://vid.me/VtRJ

The code is currently running on my site: https://tld-list.com

I've only manually tested this with window scrolling and in 'fixed' mode across a number of browsers/devices, so there's a very good chance the changes break something else.  Pull request on the way.
