### ISSUE TITLE
IE9 glitch: floatThead covers the first row on init.

### ISSUE THREAD

**Issue by MikaelPorttila** [mkoryak/floatThead#206] opened 2015-05-28 08:49 UTC
IE9 on floatThead init: the thead will start floating even though it does not need to and the placeholder
for the real thead is missing, resulting with the first row being covered by floatThead.

JSFiddle: https://jsfiddle.net/m81rjp2o/21/

**Comment by mkoryak** [comment] 2015-05-28 15:05
- you were styling by id, should be styling by class
- your first row in tbody contains colspans, you should read this: http://mkoryak.github.io/floatThead/examples/row-groups/
- using `useAbsolutePositioning:false` makes ie perform better in window scrolling

https://jsfiddle.net/m81rjp2o/25/

also, i couldnt reproduce your issue with your original code ;)

**Comment by mkoryak** [comment] 2015-06-02 14:12
closing this since my fiddle works for me, reopen if you disagree

**Closed by mkoryak** 2015-06-02 14:12 UTC
Labels: question
