### ISSUE TITLE
Overflow scrolling scrollbar goes under headers on Mac

### ISSUE THREAD

**Issue by DannyJJK** [mkoryak/floatThead#222] opened 2015-07-01 15:53 UTC
I'm not sure if this happens on Windows, but on Mac (Tested on Firefox and Chrome), the scrollbar goes underneath the headers, so when you scroll to the top, a section of the scrollbar is missing. This does not need a jsfiddle as it is clearly visible on the homepage of the website on the "Demo".
![screen shot 2015-07-01 at 16 52 00](https://cloud.githubusercontent.com/assets/11057501/8458898/9c505d66-2011-11e5-9953-36a7bc28bfb6.png)

**Comment by mkoryak** [comment] 2015-07-01 15:54
I am on a mac, and I dont see this. maybe you did something funny with your system's scrollbar settings?

**Comment by DannyJJK** [comment] 2015-07-01 15:56
Nope, this is the system default (OSX 10.10.4), the rest of the Macs in our office experience the same issue too

**Comment by mkoryak** [comment] 2015-07-01 15:58
ok, kind of hard for me to help you since I have no way to reproduce, I am on 10.9. can you run this function in your js console and tell me the result:
```js
 function scrollbarWidth() {
    var $div = $( //borrowed from anti-scroll
        '<div style="width:50px;height:50px;overflow-y:scroll;'
        + 'position:absolute;top:-200px;left:-200px;"><div style="height:100px;width:100%">'
        + '</div>'
    );
    $('body').append($div);
    var w1 = $div.innerWidth();
    var w2 = $('div', $div).innerWidth();
    $div.remove();
    return w1 - w2;
  }
```

**Comment by mkoryak** [comment] 2015-07-01 16:01
also, does the demo on this page work better in 'fixed positioning':
http://mkoryak.github.io/floatThead/examples/inner-scroll/

**Comment by DannyJJK** [comment] 2015-07-01 16:05
I just get 0 when running that code, and yeah when it's in fixed positioning the scrollbars appear on top which looks perfectly fine, I guess I should use fixed positioning

**Comment by mkoryak** [comment] 2015-07-01 16:07
So at least you have a workaround. If you can find me some code that reliably calculates the width of a scrollbar on your mac and on my mac, I will update the plugin :)

**Comment by DannyJJK** [comment] 2015-07-01 16:11
The width of the scrollbar on a Mac is zero because it auto hides and appears above the content, instead of pushing it out of the way like on Linux and Windows. I believe it can be set to work like Windows though if you go into System Preferences and set scrollbars to not auto hide (in which case they would have to have a width and push the content out of the way)

**Comment by mkoryak** [comment] 2015-07-01 16:13
My scrollbars work like that too on 10.9, yet that function does yield the correct value for me.

**Comment by mkoryak** [comment] 2015-07-06 13:08
closing since workaround exists and I cannot reproduce without updating my OS

**Closed by mkoryak** 2015-07-06 13:08 UTC
Labels: workaround
