### ISSUE TITLE
Horizontal Scrolling not working

### ISSUE THREAD

**Issue by IrvingArmenta** [mkoryak/floatThead#355] opened 2017-02-16 23:10 UTC
My issue must be pretty simple, and I apologize in advance if is something I'm just missing out, I've doing research but it seems I just can't make it work as I would like to. 

**All I need is for the table to behave exactly as bootstrap ["responsive tables"](https://www.w3schools.com/bootstrap/tryit.asp?filename=trybs_ref_table-responsive&stacked=h) behave** 

with an horizontal scrollbar only appearing when a certain width is reached, I'm not sure if the styles of the perfect-scrollbar are messing with it, but I don't think so,  here is the jsfiddle: https://jsfiddle.net/thza9whh/

- Chrome (latest)
- Windows 7
- jQuery (latest)
- floatThead (latest)

**Comment by mkoryak** [comment] 2017-02-16 23:16
See responsiveContainer option in the docs. Does that work ?

**Comment by IrvingArmenta** [comment] 2017-02-17 00:44
I just set it up on the jsfiddle; The "head" section gets outside of the container and the horizontal scroll still does not work.

**Comment by mkoryak** [comment] 2017-02-17 14:54
what should happen?

here is your fiddle without any scripts running:

https://jsfiddle.net/thza9whh/3/

i dont see a horizontal scrollbar there. should one be there? if so, then its not the scripts that are breaking it

**Comment by IrvingArmenta** [comment] 2017-02-17 17:03
Maybe is a perfect-scroll issue, I'm not sure, this is a newer version of what i want to accomplish:
https://jsfiddle.net/qyrztt4L/1/

I removed the other elements wrapping the table, and now is only the element with id  "#operationsWrap" that is wrapping it,

 The issue is, that I want only this element "#operationsWrap" to scroll both on Y and X, right now as it is in the fiddle the div with class ".operations" has a overflow: auto to scroll the whole block, I don't want that, the element on top, the element with class ".operations__head" should not scroll, only the wrapper of the table, on X only when the min-width of 870px is reached.

I understand it might not be an issue with floatThead, and also understand I'm abusing of your time, but do you have a clue of what it might be? I think I'll post an issue on perfect-scrollbar github.

Thank you

**Comment by RalucaP** [comment] 2017-02-20 19:06
First of all, thank you so much for this plugin, it's the only one working properly for me. :)

Second, I'm having a huge issue while I'm scrolling horizontally, I'm changing table's body's tds width dynamically and  I call `$table.trigger('reflow')` on this event. 
The header re-designs itself but it's not aligned with the td I'm modifying. 

If I don't call the `$table.trigger('reflow')` the header remains obviously fixed and not changing its width accordingly to the td width which also creates a weird behaviour.

Did anyone else encountered this issue and knows a solution for it?

**Comment by mkoryak** [comment] 2017-02-20 19:17
@RalucaP
Please create a new issue, I don't think your issue is related. Also if you want me to help you, please create a jsfiddle which reproduces your issue. 

Your question as it stands is impossible to answer, other than with "no, I don't have a problem like that"

**Comment by RalucaP** [comment] 2017-02-20 19:23
@mkoryak, you are right. I'm sorry for posting on this issue, I saw it was horizontal scroll related and my issue only happens while I'm scrolling horizontally but is clearly a separated one. Anyway, thanks for the fast reply :)

**Comment by mkoryak** [comment] 2017-02-20 19:48
I can probably help you with it if you can boil it down to a small fiddle, or maybe you will find the solution yourself when you do that.

**Comment by RalucaP** [comment] 2017-02-20 19:49
@mkoryak, here's the fiddle https://jsfiddle.net/qyrztt4L/6/, should I open a new issue with this?

**Comment by mkoryak** [comment] 2017-02-20 22:42
@RalucaP this is actually a bug that was fixed on master. i just published a new version. here is the updated fiddle using master:

https://jsfiddle.net/qyrztt4L/11/

cdns should catch up to new version shortly

**Comment by mkoryak** [comment] 2017-02-20 22:43
https://github.com/mkoryak/floatThead/releases/tag/2.0.3

**Comment by RalucaP** [comment] 2017-02-21 14:38
@mkoryak, you are awesome! :) I can confirm that the bug is gone and everything works perfectly now!

**Comment by mkoryak** [comment] 2017-02-23 02:07
@IrvingArmenta i am still not sure what "the problem is" your latest example works for me. maybe the new version i just pushed will solve your problems  too?

**Comment by mkoryak** [comment] 2017-02-24 04:24
closing, nothing else left for me to do here

**Closed by mkoryak** 2017-02-24 04:24 UTC
