### ISSUE TITLE
Adjusting first column width

### ISSUE THREAD

**Issue by adayth** [mkoryak/floatThead#213] opened 2015-06-03 17:31 UTC
How can the first column of a table width be adjusted?

I tried from now the next list:

-  style="width:250px;" in th, td elements
- colgroup display:none
- tried to adjust first colgroup col width via JS event with .on("floatThead"

Without applying floatThead I achieve this giving to first column th style="width:250px;"

**Comment by mkoryak** [comment] 2015-06-03 19:56
good question. I dont know, but you can try:

instead of putting the style on the first `th` put it on the first `col` in the colgroup and then `$table.trigger('reflow')`

if that doesnt work, define your own colgroup prior to running the plugin and try the above again

**Comment by mkoryak** [comment] 2015-06-04 14:13
this is a somewhat crappy solution, but it works

http://jsfiddle.net/ny2nw8zt/2/

**Comment by adayth** [comment] 2015-06-04 21:58
I'll try it but is a big table and maybe the performance won't be good

**Comment by mkoryak** [comment] 2015-06-05 01:01
I can see about adding support for doing this if the crappy solution doesnt work well, when I have time

**Comment by adayth** [comment] 2015-06-05 10:30
This hack works for me, but is an ugly solution.

If you add support for this consider adding a new settings like ```{width: [width1, width2, ..., widthN]}``` where each width will be applied for each column/colgroup. If a column width is not defined in the array, then can be set to a nice calculated value.
Maybe you can also add support for providing one width for all columns ```{width: '20'}```

Thanks for the support and development of the plugin ;)

**Comment by mkoryak** [comment] 2015-06-05 12:22
setting column widths is an idea I have considered a few times before. It turns out to be not trivial :)

The problem is that the table element doesnt always respect the widths you set on it, for example if you set a column width to be smaller than content it contains, the width will not be respected. Same goes for setting a column to be wider than a table.  I think this would be confusing to the developers who would expect the plugin to respect their settings. 

On the other hand, since I use `table-layout:fixed`, this turns off the above "smart layout" functionality. You COULD set your columns to all be 1px wide and it would look like crap.  Maybe I should go this route and let you as the developer make your table look like crap :) 

Finally this plugin supports adding/removing hiding/showing columns, which makes this a bit more complicated

**Comment by mkoryak** [comment] 2015-06-05 14:28
I threw together some code to test this and remembered why I didnt want to support it. The functionality feels broken because since you are not changing the table width, the width you set might be respected by the browser, or might not if the sum of column widths is greater than table width, or less than table width. There is some wiggle room where setting a width works as expected because the other columns can compensate for this.

I cant set the table width to make it "work" because I do not know by what amount to change it.

**Comment by adayth** [comment] 2015-06-05 16:30
I agree, in general tables are a mess and normally this will be over difficult to implement.

I noticed that the plugin adds colgroups with calculated widths, even if tables doesn't have one. I thought that column widths are being affected by colgroups, so creating a new one with an array of widths, instead of calculating it, could be a great idea. But probably I'm wrong in my deductions. I really never used colgroups, so don't blame me please ;)

**Comment by mkoryak** [comment] 2015-06-05 16:45
yes, colgroups control the widths of the columns in the table. setting a userdefined width on the cols will still cause issues if the new total width of the columns is greater/smaller than table width.

Let me show you what I mean:

https://gist.github.com/mkoryak/30afd0afbe249489fea1

use like this:
```js
        var $table = $('.fixed-table');
        var w = null;
        $table.floatThead({
            width: function($table, numCols){
                return w;
            }
        });
       
        setTimeout(function(){
            w = ["200px"];
            $table.trigger('reflow');
        }, 5000);
```

**Comment by mkoryak** [comment] 2015-06-08 21:59
closing this as wontfix. I wish I had a better answer for you.

**Closed by mkoryak** 2015-06-08 21:59 UTC
Labels: enhancement, wontfix

**Comment by adayth** [comment] 2015-06-08 22:04
No problem Misha. I understand the problems about adding this
functionality.
You did a good effort to help me and with your help I solved my most
important issue.

Thank you for your great support =)

2015-06-08 22:59 GMT+01:00 Misha Koryak <notifications@github.com>:

> closing this as wontfix. I wish I had a better answer for you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mkoryak/floatThead/issues/213#issuecomment-110154262>.
>



-- 
Aday Talavera Hierro - Consultoría y desarrollo informático
Web: http://www.felfo.com  -  Email: aday.talavera@gmail.com
